# Generated by Django 3.2.4 on 2021-06-29 21:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingObjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='BookingObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='Название объекта')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('daily-payment', 'Посуточная оплата'), ('hourly-payment', 'Почасовая оплата'), ('per-minute-payment', 'Поминутная оплата')], max_length=20, verbose_name='Тип оплаты')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_objects', to='booking_object.bookingobjecttype', verbose_name='Тип объекта')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(editable=False, max_length=80, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Описание услуги')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_object.bookingobject', verbose_name='Объект бронирования')),
            ],
        ),
    ]
