# Generated by Django 3.2.4 on 2021-08-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_object', '0001_initial'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_object',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_objects',
            field=models.ManyToManyField(to='booking_object.BookingObject', verbose_name='Объекты бронирования'),
        ),
    ]
