version: '3'

services:
  postgres:
    image: 'postgres:alpine'
    container_name: booking_postgres
    env_file:
      - .env.postgres
    volumes:
      - pgdata:/var/lib/posgresql/data
    restart: always

  backend:
    image: 'booking/backend'
    container_name: booking_backend
    env_file:
      - .env.backend
    depends_on:
      - postgres
    restart: always

  nginx:
    image: 'booking/nginx'
    container_name: booking_nginx
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: always


volumes:
  pgdata: {}
