# Generated by Django 3.2.4 on 2021-06-29 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта')),
                ('additional_info', models.TextField(blank=True, max_length=300, null=True, verbose_name='Дополнительная информация')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Флаг удаленного клиента')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
